### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by Optiqx** [YaNesyTortiK/Kodik-Download-Watch#1]
Если есть свободное время, желание иметь свой аниме проект как для портфолио, так и для души, развития/тестирования идей, медийки +-, напиши tg @optiqxc - есть предложение, вдруг заинтересует :)

**Comment by YaNesyTortiK** [comment]
Предложение конечно интересное, но так как не относится к какой-либо ошибке в программе - закрываю.
