### ISSUE TITLE
An error occurs when trying to start

### ISSUE THREAD

**Issue by makcoys** [YaNesyTortiK/Kodik-Download-Watch#2]
Возникает ошибка при попытке запуска main.py
![Скриншот 14-08-2024 212441](https://github.com/user-attachments/assets/8496184f-02dd-4896-a2b9-2ef3c9417951)

Traceback (most recent call last):
  File "C:\Users\makco\OneDrive\Рабочий стол\Kodik-Download-Watch-main\main.py", line 5, in <module>
    from fast_download import clear_tmp, fast_download, get_path
  File "C:\Users\makco\OneDrive\Рабочий стол\Kodik-Download-Watch-main\fast_download.py", line 73
    subprocess.call(f'ffmpeg -y{" -hwaccel "+hwaccel if not hwaccel is None else '' } -f concat -safe 0 -i {directory}files.txt -c copy {directory}{name}.mp4', stderr=subprocess.DEVNULL)
                                                                                                                                                              ^
SyntaxError: f-string: expecting '}'
Удалось пофиксить заменив одинарные кавычки (') на двойные ("): -y{" -hwaccel "+hwaccel if not hwaccel is None else "" }
![Скриншот 14-08-2024 213210](https://github.com/user-attachments/assets/63d2fc8a-2ce5-4f95-95b2-b308f64a2274)
![Скриншот 14-08-2024 213244](https://github.com/user-attachments/assets/846fa829-600c-4aa6-bd86-b7e12cd13b9c)

**Comment by YaNesyTortiK** [comment]
Спасибо за найденную ошибку и детальное описание, исправлено.
